services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    command: ["mariadbd", "--max-connections=100", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_bin"]
    networks:
      - default
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=openfga
      - MARIADB_USER=openfga
      - MARIADB_PASSWORD=openfga
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    depends_on:
      mariadb:
        condition: service_healthy
    image: openfga/openfga:local
    container_name: migrate-mariadb
    environment:
      - OPENFGA_DATASTORE_ENGINE=mariadb
      - OPENFGA_DATASTORE_URI=openfga:openfga@tcp(mariadb:3306)/openfga?parseTime=true
    command: migrate
    networks:
      - default

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:local
    container_name: openfga-mariadb
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=mariadb
      - OPENFGA_DATASTORE_URI=openfga:openfga@tcp(mariadb:3306)/openfga?parseTime=true
      - OPENFGA_DATASTORE_MAX_OPEN_CONNS=100
      - OPENFGA_PLAYGROUND_ENABLED=true
    networks:
      - default
    ports:
      - "8080:8080" # http
      - "8081:8081" # grpc
      - "3000:3000" # playground
      - "2112:2112" # prometheus metrics
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/grpc_health_probe",
          "-addr=openfga-mariadb:8081"
        ]
      interval: 5s
      timeout: 30s
      retries: 3

networks:
  default:
